AllCops:
  Excludes:
    - vendor/**
    - bin/**
    - tmp/**
Encoding:
  Enabled: false
ClassLength:
  Enabled: false
MethodLength:
  Enabled: false
LineLength:
  Enabled: false
Lambda:
  Enabled: false
IfUnlessModifier:
  Enabled: false